### ISSUE TITLE
main.py won't run

### ISSUE THREAD

**Issue by nbruner04** [ev1l0rd/discord-cmus-status#1]
I installed all of the prerequisites for this program but when I try to run main.py like it says to do in the README, this error message pops up.
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import rpc
  File "/home/nathan/discord-cmus-status/rpc.py", line 17
    self.sock_reader: asyncio.StreamReader = None
                    ^
SyntaxError: invalid syntax
`
Anyone know how to fix this?

**Comment by frankdugan3** [comment]
@nbruner04 Are you running with Python 3? `python3 main.py`

**Comment by noirscape** [comment]
Please use the version over at [discord-cmus-status](https://github.com/discord-cmus-status/discord-cmus-status).
